#!/usr/bin/env sh

echo 'Setting up your machine...'

OSX_VERSION=$(sw_vers | grep ProductVersion | awk -F: '{print $2}')

if [[ $OSX_VERSION =~ "10.8*" ]]; then
  echo "You're not running OS X 10.8 (Mountain Lion)"
  read -p "This script is meant to be run on Mountain Lion!"
  exit 0
fi

if [ -f "/Developer/Library/uninstall-tools" ]; then
  echo -p "Xcode pre-4.3 detected."
elif
  [ -f "/usr/bin/gcc" ]; then
  echo "Xcode 4.3+ detected."
else
  read -p "Please install Xcode and re-run this script"
  exit 0
fi

echo 'Cloning mac script and setting correct permissions'
  curl -s https://raw.github.com/esparkman/PairMeUp/master/mac -o /tmp/mac_install
  chmod 0700 /tmp/mac_install
  . /tmp/mac_install
