#!/usr/bin/env sh

echo 'Setting up your machine...'

if [ -f "/Developer/Library/uninstall-tools" ]; then
  echo -p "Xcode pre-4.3 detected."
elif
  [ -f "/usr/bin/gcc" ]; then
  echo "Xcode 4.3+ detected."
else
  echo "Please install Xcode and re-run this script"
  exit 0
fi

echo 'Cloning mac script and setting correct permissions'
  curl -s https://raw.github.com/esparkman/PairMeUp/master/mac -o /tmp/mac_install
  chmod 0700 /tmp/mac_install
  . /tmp/mac_install
